[package]
name = "belladonna-sherbet"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", default-features = true, features = ["dynamic_linking"] }

[lints.clippy]
to_many_arguments = "allow"
type_complexity = "allow"
nonstandard_macro_braces = "warn"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
strip = true
opt-level = 3
