[package]
name = "belladonna-sherbet"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
bevy = { version = "0.19", features = ["dynamic_linking"] }
bevy-inspector-egui = { version = "0.37", optional = true }
egui_dock = { version = "0.19" , optional = true}
bevy_skein = "0.6"
avian3d = "0.7.0"
bevy-tnua-avian3d = "0.12.0"
bevy-tnua = "0.32.0"
bevy_yarnspinner = "0.9.0"
bevy_yarnspinner_example_dialogue_view = "0.9.0"
bevy-persistent = { version = "0.11.0", features = ["all"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_with = "3.21.0"

[features]
default = []
dev-tools = [
    "dep:bevy-inspector-egui",
    "dep:egui_dock"
]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
features = "dev-tools"
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"
